# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MAIN_DETECTOR_MOV_GUI.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGroupBox,
    QLineEdit, QMainWindow, QMenuBar, QPlainTextEdit,
    QPushButton, QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(961, 622)
        MainWindow.setMinimumSize(QSize(961, 622))
        MainWindow.setMaximumSize(QSize(961, 622))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox2 = QGroupBox(self.centralwidget)
        self.groupBox2.setObjectName(u"groupBox2")
        self.groupBox2.setGeometry(QRect(10, 100, 941, 221))
        palette = QPalette()
        self.groupBox2.setPalette(palette)
        font = QFont()
        font.setBold(True)
        self.groupBox2.setFont(font)
        self.groupBox2.setFlat(False)
        self.groupBox2.setCheckable(False)
        self.groupBox3 = QGroupBox(self.groupBox2)
        self.groupBox3.setObjectName(u"groupBox3")
        self.groupBox3.setGeometry(QRect(10, 20, 921, 61))
        self.groupBox3.setCheckable(False)
        self.lineEdit1 = QLineEdit(self.groupBox3)
        self.lineEdit1.setObjectName(u"lineEdit1")
        self.lineEdit1.setEnabled(False)
        self.lineEdit1.setGeometry(QRect(10, 20, 801, 20))
        font1 = QFont()
        font1.setBold(False)
        self.lineEdit1.setFont(font1)
        self.pushButton3 = QPushButton(self.groupBox3)
        self.pushButton3.setObjectName(u"pushButton3")
        self.pushButton3.setGeometry(QRect(820, 20, 93, 31))
        palette1 = QPalette()
        brush = QBrush(QColor(170, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(120, 120, 120, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.pushButton3.setPalette(palette1)
        font2 = QFont()
        font2.setBold(True)
        font2.setUnderline(False)
        self.pushButton3.setFont(font2)
        self.groupBox4 = QGroupBox(self.groupBox2)
        self.groupBox4.setObjectName(u"groupBox4")
        self.groupBox4.setGeometry(QRect(10, 90, 211, 51))
        self.lineEdit2 = QLineEdit(self.groupBox4)
        self.lineEdit2.setObjectName(u"lineEdit2")
        self.lineEdit2.setEnabled(True)
        self.lineEdit2.setGeometry(QRect(10, 20, 191, 20))
        self.lineEdit2.setFont(font1)
        self.groupBox5 = QGroupBox(self.groupBox2)
        self.groupBox5.setObjectName(u"groupBox5")
        self.groupBox5.setGeometry(QRect(230, 90, 211, 51))
        self.lineEdit3 = QLineEdit(self.groupBox5)
        self.lineEdit3.setObjectName(u"lineEdit3")
        self.lineEdit3.setEnabled(True)
        self.lineEdit3.setGeometry(QRect(10, 20, 191, 20))
        self.lineEdit3.setFont(font1)
        self.groupBox6 = QGroupBox(self.groupBox2)
        self.groupBox6.setObjectName(u"groupBox6")
        self.groupBox6.setGeometry(QRect(450, 90, 211, 51))
        self.lineEdit4 = QLineEdit(self.groupBox6)
        self.lineEdit4.setObjectName(u"lineEdit4")
        self.lineEdit4.setEnabled(True)
        self.lineEdit4.setGeometry(QRect(10, 20, 171, 20))
        self.lineEdit4.setFont(font1)
        self.checkBox1 = QCheckBox(self.groupBox6)
        self.checkBox1.setObjectName(u"checkBox1")
        self.checkBox1.setGeometry(QRect(190, 20, 21, 16))
        self.checkBox1.setChecked(True)
        self.groupBox7 = QGroupBox(self.groupBox2)
        self.groupBox7.setObjectName(u"groupBox7")
        self.groupBox7.setGeometry(QRect(670, 90, 211, 51))
        self.lineEdit5 = QLineEdit(self.groupBox7)
        self.lineEdit5.setObjectName(u"lineEdit5")
        self.lineEdit5.setEnabled(True)
        self.lineEdit5.setGeometry(QRect(10, 20, 191, 20))
        self.lineEdit5.setFont(font1)
        self.groupBox12 = QGroupBox(self.groupBox2)
        self.groupBox12.setObjectName(u"groupBox12")
        self.groupBox12.setGeometry(QRect(890, 90, 41, 51))
        self.checkBox3 = QCheckBox(self.groupBox12)
        self.checkBox3.setObjectName(u"checkBox3")
        self.checkBox3.setGeometry(QRect(10, 20, 21, 16))
        self.checkBox3.setChecked(True)
        self.groupBox13 = QGroupBox(self.groupBox2)
        self.groupBox13.setObjectName(u"groupBox13")
        self.groupBox13.setGeometry(QRect(10, 150, 371, 61))
        self.lineEdit8 = QLineEdit(self.groupBox13)
        self.lineEdit8.setObjectName(u"lineEdit8")
        self.lineEdit8.setEnabled(False)
        self.lineEdit8.setGeometry(QRect(10, 20, 61, 20))
        self.lineEdit9 = QLineEdit(self.groupBox13)
        self.lineEdit9.setObjectName(u"lineEdit9")
        self.lineEdit9.setEnabled(False)
        self.lineEdit9.setGeometry(QRect(70, 20, 61, 20))
        self.pushButton8 = QPushButton(self.groupBox13)
        self.pushButton8.setObjectName(u"pushButton8")
        self.pushButton8.setEnabled(True)
        self.pushButton8.setGeometry(QRect(262, 20, 101, 31))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.pushButton8.setPalette(palette2)
        self.pushButton8.setFont(font2)
        self.lineEdit10 = QLineEdit(self.groupBox13)
        self.lineEdit10.setObjectName(u"lineEdit10")
        self.lineEdit10.setEnabled(False)
        self.lineEdit10.setGeometry(QRect(140, 20, 61, 20))
        self.lineEdit11 = QLineEdit(self.groupBox13)
        self.lineEdit11.setObjectName(u"lineEdit11")
        self.lineEdit11.setEnabled(False)
        self.lineEdit11.setGeometry(QRect(190, 20, 61, 20))
        self.groupBox14 = QGroupBox(self.groupBox2)
        self.groupBox14.setObjectName(u"groupBox14")
        self.groupBox14.setGeometry(QRect(390, 150, 141, 61))
        self.comboBox4 = QComboBox(self.groupBox14)
        self.comboBox4.setObjectName(u"comboBox4")
        self.comboBox4.setGeometry(QRect(10, 20, 121, 21))
        self.groupBox15 = QGroupBox(self.groupBox2)
        self.groupBox15.setObjectName(u"groupBox15")
        self.groupBox15.setGeometry(QRect(540, 150, 141, 61))
        self.comboBox2 = QComboBox(self.groupBox15)
        self.comboBox2.setObjectName(u"comboBox2")
        self.comboBox2.setGeometry(QRect(10, 20, 121, 21))
        self.groupBox6_2 = QGroupBox(self.groupBox2)
        self.groupBox6_2.setObjectName(u"groupBox6_2")
        self.groupBox6_2.setGeometry(QRect(690, 150, 141, 61))
        self.comboBox3 = QComboBox(self.groupBox6_2)
        self.comboBox3.setObjectName(u"comboBox3")
        self.comboBox3.setGeometry(QRect(10, 20, 121, 21))
        self.pushButton9 = QPushButton(self.groupBox2)
        self.pushButton9.setObjectName(u"pushButton9")
        self.pushButton9.setEnabled(True)
        self.pushButton9.setGeometry(QRect(840, 150, 93, 31))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.pushButton9.setPalette(palette3)
        self.pushButton9.setFont(font2)
        self.pushButton10 = QPushButton(self.groupBox2)
        self.pushButton10.setObjectName(u"pushButton10")
        self.pushButton10.setEnabled(False)
        self.pushButton10.setGeometry(QRect(840, 180, 93, 31))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.pushButton10.setPalette(palette4)
        self.pushButton10.setFont(font2)
        self.groupBox1 = QGroupBox(self.centralwidget)
        self.groupBox1.setObjectName(u"groupBox1")
        self.groupBox1.setGeometry(QRect(10, 10, 621, 81))
        palette5 = QPalette()
        self.groupBox1.setPalette(palette5)
        self.groupBox1.setFont(font)
        self.groupBox1.setAutoFillBackground(False)
        self.pushButton2 = QPushButton(self.groupBox1)
        self.pushButton2.setObjectName(u"pushButton2")
        self.pushButton2.setEnabled(False)
        self.pushButton2.setGeometry(QRect(110, 30, 93, 31))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.pushButton2.setPalette(palette6)
        self.pushButton2.setFont(font2)
        self.pushButton1 = QPushButton(self.groupBox1)
        self.pushButton1.setObjectName(u"pushButton1")
        self.pushButton1.setEnabled(True)
        self.pushButton1.setGeometry(QRect(10, 30, 93, 31))
        self.pushButton1.setFont(font)
        self.groupBox9 = QGroupBox(self.groupBox1)
        self.groupBox9.setObjectName(u"groupBox9")
        self.groupBox9.setGeometry(QRect(210, 20, 61, 51))
        self.checkBox2 = QCheckBox(self.groupBox9)
        self.checkBox2.setObjectName(u"checkBox2")
        self.checkBox2.setGeometry(QRect(10, 20, 75, 16))
        self.groupBox10 = QGroupBox(self.groupBox1)
        self.groupBox10.setObjectName(u"groupBox10")
        self.groupBox10.setGeometry(QRect(280, 20, 111, 51))
        self.lineEdit6 = QLineEdit(self.groupBox10)
        self.lineEdit6.setObjectName(u"lineEdit6")
        self.lineEdit6.setEnabled(False)
        self.lineEdit6.setGeometry(QRect(10, 20, 91, 20))
        self.lineEdit6.setFont(font1)
        self.groupBox11 = QGroupBox(self.groupBox1)
        self.groupBox11.setObjectName(u"groupBox11")
        self.groupBox11.setGeometry(QRect(400, 20, 111, 51))
        self.lineEdit7 = QLineEdit(self.groupBox11)
        self.lineEdit7.setObjectName(u"lineEdit7")
        self.lineEdit7.setEnabled(False)
        self.lineEdit7.setGeometry(QRect(10, 20, 91, 20))
        self.lineEdit7.setFont(font1)
        self.pushButton7 = QPushButton(self.groupBox1)
        self.pushButton7.setObjectName(u"pushButton7")
        self.pushButton7.setEnabled(True)
        self.pushButton7.setGeometry(QRect(520, 30, 93, 31))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.pushButton7.setPalette(palette7)
        self.pushButton7.setFont(font2)
        self.plainTextEdit1 = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit1.setObjectName(u"plainTextEdit1")
        self.plainTextEdit1.setGeometry(QRect(10, 330, 941, 241))
        font3 = QFont()
        font3.setPointSize(12)
        self.plainTextEdit1.setFont(font3)
        self.plainTextEdit1.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.plainTextEdit1.setReadOnly(True)
        self.groupBox8 = QGroupBox(self.centralwidget)
        self.groupBox8.setObjectName(u"groupBox8")
        self.groupBox8.setGeometry(QRect(640, 10, 311, 81))
        palette8 = QPalette()
        self.groupBox8.setPalette(palette8)
        self.groupBox8.setFont(font)
        self.pushButton5 = QPushButton(self.groupBox8)
        self.pushButton5.setObjectName(u"pushButton5")
        self.pushButton5.setGeometry(QRect(110, 30, 93, 31))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.pushButton5.setPalette(palette9)
        self.pushButton5.setFont(font2)
        self.pushButton4 = QPushButton(self.groupBox8)
        self.pushButton4.setObjectName(u"pushButton4")
        self.pushButton4.setEnabled(True)
        self.pushButton4.setGeometry(QRect(10, 30, 93, 31))
        self.pushButton4.setFont(font)
        self.pushButton6 = QPushButton(self.groupBox8)
        self.pushButton6.setObjectName(u"pushButton6")
        self.pushButton6.setGeometry(QRect(210, 30, 93, 31))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.pushButton6.setPalette(palette10)
        self.pushButton6.setFont(font2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 961, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.pushButton3.setDefault(False)
        self.pushButton8.setDefault(False)
        self.pushButton9.setDefault(False)
        self.pushButton10.setDefault(False)
        self.pushButton2.setDefault(False)
        self.pushButton1.setDefault(False)
        self.pushButton7.setDefault(False)
        self.pushButton5.setDefault(False)
        self.pushButton4.setDefault(False)
        self.pushButton6.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"cflow-ad GUI", None))
        self.groupBox2.setTitle(QCoreApplication.translate("MainWindow", u"SETTINGS", None))
        self.groupBox3.setTitle(QCoreApplication.translate("MainWindow", u"CHECKPOINT FILE", None))
        self.pushButton3.setText(QCoreApplication.translate("MainWindow", u"OPEN", None))
        self.groupBox4.setTitle(QCoreApplication.translate("MainWindow", u"KERNEL SIZE", None))
        self.lineEdit2.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.groupBox5.setTitle(QCoreApplication.translate("MainWindow", u"THRESHOLD FOR DETECTION", None))
        self.lineEdit3.setText(QCoreApplication.translate("MainWindow", u"2.0", None))
        self.groupBox6.setTitle(QCoreApplication.translate("MainWindow", u"THRESHOLD FOR AREA SIZE", None))
        self.lineEdit4.setText(QCoreApplication.translate("MainWindow", u"500", None))
        self.checkBox1.setText("")
        self.groupBox7.setTitle(QCoreApplication.translate("MainWindow", u"NON SIMILER THRESHOLD", None))
        self.lineEdit5.setText(QCoreApplication.translate("MainWindow", u"0.5", None))
        self.groupBox12.setTitle(QCoreApplication.translate("MainWindow", u"LOG", None))
        self.checkBox3.setText("")
        self.groupBox13.setTitle(QCoreApplication.translate("MainWindow", u"TRIM POSITION AND SIZE", None))
        self.pushButton8.setText(QCoreApplication.translate("MainWindow", u"CLEAR", None))
        self.groupBox14.setTitle(QCoreApplication.translate("MainWindow", u"DETECTION SIZE", None))
        self.groupBox15.setTitle(QCoreApplication.translate("MainWindow", u"VIDEO SIZE", None))
        self.groupBox6_2.setTitle(QCoreApplication.translate("MainWindow", u"CAMERA ", None))
        self.pushButton9.setText(QCoreApplication.translate("MainWindow", u"TAKE PICTURE", None))
        self.pushButton10.setText(QCoreApplication.translate("MainWindow", u"TEST PICTURE", None))
        self.groupBox1.setTitle(QCoreApplication.translate("MainWindow", u"EXCUTE", None))
        self.pushButton2.setText(QCoreApplication.translate("MainWindow", u"STOP", None))
        self.pushButton1.setText(QCoreApplication.translate("MainWindow", u"START", None))
        self.groupBox9.setTitle(QCoreApplication.translate("MainWindow", u"DEBUG", None))
        self.checkBox2.setText("")
        self.groupBox10.setTitle(QCoreApplication.translate("MainWindow", u"COUNTER", None))
        self.lineEdit6.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.groupBox11.setTitle(QCoreApplication.translate("MainWindow", u"NG", None))
        self.lineEdit7.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.pushButton7.setText(QCoreApplication.translate("MainWindow", u"CHECK", None))
        self.plainTextEdit1.setPlainText("")
        self.groupBox8.setTitle(QCoreApplication.translate("MainWindow", u"STATE", None))
        self.pushButton5.setText(QCoreApplication.translate("MainWindow", u"SAVE", None))
        self.pushButton4.setText(QCoreApplication.translate("MainWindow", u"LOAD", None))
        self.pushButton6.setText(QCoreApplication.translate("MainWindow", u"DEFAULT", None))
    # retranslateUi

